### ISSUE TITLE
数组成员引用下标超出定义范围

### ISSUE THREAD

**Issue by ghost** [liaosunny123/EpicMoMiraiG#3]
emg start报错，内容如下，已更新源和更新

---------------------------
错误
---------------------------
运行时出错!

错误代码：1

错误信息：数组成员引用下标超出定义范围

67184310, 209

---------------------------
确定   
---------------------------

**Comment by liaosunny123** [comment]
检测环境是否正常?
按照如下方式检测：在emg菜单里面：程序-环境检测
如果错误，请在emg提供的网站下载java，推荐下载地址为：网盾科技电信下载。emg推荐安装 java 15.0.2 64bit
如果正常，请提供logs文件夹下最新时间的log文件和Logs文件夹下最新的log文件方便进一步跟进问题。

**Comment by ghost** [comment]
emm，很神奇，我重新更新了一次就没有问题了
