### ISSUE TITLE
4.0一直重复更新，关不掉必须重启

### ISSUE THREAD

**Issue by SweetlandDSL** [liaosunny123/EpicMoMiraiG#7]

**Comment by liaosunny123** [comment]
EMG 4.0的更新似乎成为了祖传bug，这可能是由于EMG.exe本体对于更新进程未完全结束造成的。
# 解决方案
在彻底关闭EMG 4.0的情况下单独运行Update.exe程序，或者前往EMG发布页:emg.epicmo.cn下载最新版
# 预期解决
会在下个版本进行一次彻底的修复，此Bug反馈人数有一定的规模了
# 另外
由于EMG正在全力推进5.0的研发，对于现有bug修复较为缓慢

**Comment by liaosunny123** [comment]
EMG 4.0的更新似乎成为了祖传bug，这可能是由于EMG.exe本体对于更新进程未完全结束造成的。
# 解决方案
在彻底关闭EMG 4.0的情况下单独运行Update.exe程序，或者前往EMG发布页:emg.epicmo.cn下载最新版
# 预期解决
会在下个版本进行一次彻底的修复，此Bug反馈人数有一定的规模了
# 另外
由于EMG正在全力推进5.0的研发，对于现有bug修复较为缓慢

**Comment by SweetlandDSL** [comment]
> EMG 4.0的更新似乎成为了祖传bug，这可能是由于EMG.exe本体对于更新进程未完全结束造成的。
> 
> # 解决方案
> 在彻底关闭EMG 4.0的情况下单独运行Update.exe程序，或者前往EMG发布页:emg.epicmo.cn下载最新版
> 
> # 预期解决
> 会在下个版本进行一次彻底的修复，此Bug反馈人数有一定的规模了
> 
> # 另外
> 由于EMG正在全力推进5.0的研发，对于现有bug修复较为缓慢

关闭EMG单独运行Update依旧无法解决BUG，期待5.0，谢谢分享，辛苦了

**Comment by liaosunny123** [comment]
> > EMG 4.0的更新似乎成为了祖传bug，这可能是由于EMG.exe本体对于更新进程未完全结束造成的。
> > # 解决方案
> > 在彻底关闭EMG 4.0的情况下单独运行Update.exe程序，或者前往EMG发布页:emg.epicmo.cn下载最新版
> > # 预期解决
> > 会在下个版本进行一次彻底的修复，此Bug反馈人数有一定的规模了
> > # 另外
> > 由于EMG正在全力推进5.0的研发，对于现有bug修复较为缓慢
> 
> 关闭EMG单独运行Update依旧无法解决BUG，期待5.0，谢谢分享，辛苦了

**抱歉，我们发现我们在PUSH的时候错误的把Version13标志上传为Version14标志，现已改正！**
**再次运行Update即可！**
感谢支持，不过我们仍然会优化Update，它本身也存在一定的逻辑错误
如果想要了解更多的最新消息可以进入EMG用户群：811098227

**Comment by SweetlandDSL** [comment]
> > > EMG 4.0的更新似乎成为了祖传bug，这可能是由于EMG.exe本体对于更新进程未完全结束造成的。
> > > # 解决方案
> > > 在彻底关闭EMG 4.0的情况下单独运行Update.exe程序，或者前往EMG发布页:emg.epicmo.cn下载最新版
> > > # 预期解决
> > > 会在下个版本进行一次彻底的修复，此Bug反馈人数有一定的规模了
> > > # 另外
> > > 由于EMG正在全力推进5.0的研发，对于现有bug修复较为缓慢
> > 
> > 
> > 关闭EMG单独运行Update依旧无法解决BUG，期待5.0，谢谢分享，辛苦了
> 
> **抱歉，我们发现我们在PUSH的时候错误的把Version13标志上传为Version14标志，现已改正！**
> **再次运行Update即可！**
> 感谢支持，不过我们仍然会优化Update，它本身也存在一定的逻辑错误
> 如果想要了解更多的最新消息可以进入EMG用户群：811098227

完美解决，谢谢分享
